### ISSUE TITLE
(http://www.ciwmhub.ciwm.com/Moodle/login) not working

### ISSUE THREAD

**Issue by ElaineMills** [CIWM/CIWM-Hub#4] opened 2015-07-17 08:46 UTC
i have tried to log into the above site this morning following a requesdt from a customer to check whether one of her colleagues has done the WasteSmart course and I am not able to get into it. Anna has tried and she can get to a webpage but there is nothing useable on it. are there any changes going on at the minute that mean we cannot get into this? I have ty

the error I get is below 

This web page is not available

ERR_NAME_NOT_RESOLVED
Hide details
The server at www.ciwmhub.ciwm.com can't be found because the DNS look-up failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network.

**Comment by ElaineMills** [comment] 2015-07-17 08:49
It looks as though it is a www "look-up" issue with Vivid server. Try http://ciwmhub.ciwm.co.uk/ without "www" and that should work. I will contact Vivid to let them know. Let me know if this solution works.

**Comment by nick69g** [comment] 2015-07-17 08:49
It looks as though it is a www "look-up" issue with Vivid server. Try http://ciwmhub.ciwm.co.uk/ without "www" and that should work. I will contact Vivid to let them know. Let me know if this solution works.

**Comment by nick69g** [comment] 2015-07-17 09:05
Vivid have responded to say that they "will get back to me later today on this issue".

**Comment by RobBresler** [comment] 2015-07-17 10:07
Have CIWM been able to login without the www?



Sent from Samsung Mobile on O2


-------- Original message --------

**Comment by nick69g** [comment] 2015-07-17 10:09
Hi Rob

I've not heard either way -I asked Elaine to let me know.



*Nick Garrod*

m 07867 557 801 e nick69g@icloud.com w nickgarrod.org.uk

The information contained in this email is intended solely for the 
addressee(s). If you are not the intended recipient, please contact the 
sender via return email and delete this copy. Email is not 
necessarily secure and the sender does not accept responsibility for any 
changes made to this message after it was sent or for any virus which 
has been undetected or added to this message in transmission.

Contact me: Skype nickg69

**Comment by ElaineMills** [comment] 2015-07-17 10:12
Sorry I got distracted with something else! Yes I have managed to get in now. 

do you want me to close this issue or leave it open until Nick had heard back from Vivid?

**Comment by nick69g** [comment] 2015-07-17 10:14
Just replied to say yes...


Sorry I got distracted with something else! Yes I have managed to get in 
now.

do you want me to close this issue or leave it open until Nick had heard 
back from Vivid?




*Nick Garrod*

m 07867 557 801 e nick69g@icloud.com w nickgarrod.org.uk

The information contained in this email is intended solely for the 
addressee(s). If you are not the intended recipient, please contact the 
sender via return email and delete this copy. Email is not 
necessarily secure and the sender does not accept responsibility for any 
changes made to this message after it was sent or for any virus which 
has been undetected or added to this message in transmission.

Contact me: Skype nickg69

**Comment by nick69g** [comment] 2015-07-17 10:16
Thanks Elaine. Leave the issue open until Vivid have comeback to me with a response. We are moving the servers on Monday so that should clear the "issue" anyway.

**Comment by nick69g** [comment] 2015-07-20 17:07
Vivid says... "The URL with www on will not have worked previously as the CIWM Hub part is a sub domain and therefore, cannot have www proceeding it. For this reason, the error messages occurs. The URL link that does work, has this element omitted. "

I think we've probably just never noticed this before. We may be able to resolve this when the website migrates to a new server happening tomorrow.

**Closed by nick69g** 2015-07-20 17:07 UTC
Labels: bug, help wanted

**Comment by AnnaHavard** [comment] 2015-07-20 17:17
Thanks nick, are we anticipating any downtime with the server move?

Sent from my iPhone



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image201ba1.JPG@5ecad92e.49bded9c]<http://>

[cid:imageb3dffe.PNG@68cffdc7.42b25224]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

On 20 Jul 2015, at 18:08, Nick Garrod <notifications@github.com<mailto:notifications@github.com>> wrote:


Vivid says... "The URL with www on will not have worked previously as the CIWM Hub part is a sub domain and therefore, cannot have www proceeding it. For this reason, the error messages occurs. The URL link that does work, has this element omitted. "

I think we've probably just never noticed this before. We may be able to resolve this when the website migrates to a new server happening tomorrow.

**Comment by nick69g** [comment] 2015-07-20 18:28
No. Maybe a few mins.

----------------------------------
Nick Garrod
e: nick.garrod@cloudsustainability.com<mailto:nick.garrod@cloudsustainability.com>
m: 07712 331789
s: nickg69

This email has been sent from my iPhone so please excuse any typos!

On 20 Jul 2015, at 18:17, AnnaHavard <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks nick, are we anticipating any downtime with the server move?

Sent from my iPhone



Anna Havard
Client Relationship Manager
CIWM Enterprises Ltd

Tel: +44 (0)1604 823347
Fax: +44 (0)1604 604467
Email: Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk><mailto:Anna.Havard@ciwm.co.uk>
Web: www.ciwm.co.uk<http://www.ciwm.co.uk><http://www.ciwm.co.uk>




[cid:image201ba1.JPG@5ecad92e.49bded9c]<http://>

[cid:imageb3dffe.PNG@68cffdc7.42b25224]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

On 20 Jul 2015, at 18:08, Nick Garrod <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Vivid says... "The URL with www on will not have worked previously as the CIWM Hub part is a sub domain and therefore, cannot have www proceeding it. For this reason, the error messages occurs. The URL link that does work, has this element omitted. "

I think we've probably just never noticed this before. We may be able to resolve this when the website migrates to a new server happening tomorrow.

-
Reply to this email directly or view it on GitHub<https://github.com/CIWM/CIWM-Hub/issues/4#issuecomment-122954453>.





-

**Comment by AnnaHavard** [comment] 2015-07-20 19:08
Thanks Nick

Sent from my iPhone



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image75d665.JPG@eff07e2c.4b929613]<http://>

[cid:image961839.PNG@9f2784d3.40be8a14]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

On 20 Jul 2015, at 19:29, Nick Garrod <notifications@github.com<mailto:notifications@github.com>> wrote:

No. Maybe a few mins.

----------------------------------
Nick Garrod
e: nick.garrod@cloudsustainability.com<mailto:nick.garrod@cloudsustainability.com><mailto:nick.garrod@cloudsustainability.com>
m: 07712 331789
s: nickg69

This email has been sent from my iPhone so please excuse any typos!

On 20 Jul 2015, at 18:17, AnnaHavard <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Thanks nick, are we anticipating any downtime with the server move?

Sent from my iPhone



Anna Havard
Client Relationship Manager
CIWM Enterprises Ltd

Tel: +44 (0)1604 823347
Fax: +44 (0)1604 604467
Email: Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk><mailto:Anna.Havard@ciwm.co.uk><mailto:Anna.Havard@ciwm.co.uk>
Web: www.ciwm.co.uk<http://www.ciwm.co.uk><http://www.ciwm.co.uk><http://www.ciwm.co.uk>




[cid:image201ba1.JPG@5ecad92e.49bded9c]<http://>

[cid:imageb3dffe.PNG@68cffdc7.42b25224]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

On 20 Jul 2015, at 18:08, Nick Garrod <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Vivid says... "The URL with www on will not have worked previously as the CIWM Hub part is a sub domain and therefore, cannot have www proceeding it. For this reason, the error messages occurs. The URL link that does work, has this element omitted. "

I think we've probably just never noticed this before. We may be able to resolve this when the website migrates to a new server happening tomorrow.

-
Reply to this email directly or view it on GitHub<https://github.com/CIWM/CIWM-Hub/issues/4#issuecomment-122954453>.





-

**Comment by AnnaHavard** [comment] 2015-07-21 14:55
Hi Nick

I’ve replied to this thread as I’m a bit confused by the message you’ve just sent to say the hub isn’t available given that you said last night that there wouldn’t be any downtime?



From: Nick Garrod [mailto:nick.garrod@revisesustainability.com]
Sent: 21 July 2015 15:37
To: Anna Havard; Elaine Mills
Subject: CIWM Server Migration

Hello

The CIWM Moodle database has now been exported and is currently being transferred to the new server. The learner can currently log into the CIWM Hub as normal, but if they attempt to access an eLeaning module within their account they will get the message:

The CIWM Hub is currently being updated onto a new server and is therefore now unavailable. Please come back soon as it should be up and running later this evening. It may however be unavailable until 9am tomorrow morning.

We do not expect eLearning access to be unavailable for too long and should be up and run again within the next hour or so, but have given longer timescales to be sure. The reason for putting Moodle into maintenace mode is to prevent learner acccess which may record course progress which would not now get trasferred to the new server; the actual server swap "down time" will be quick.

This only affects CIWM Hub eLearning access, the CIWM Client Hub is already on the new server and is not effected.

Regards.
Nick
________________________________

CIWM and CIWM Enterprises Ltd email security by www.MessageStream.com<http://www.MessageStream.com>





        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image92bc69.JPG@45c5648c.4f9c501d]<http://>

[cid:image4826c8.PNG@1b8512ac.47b71f57]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment] 2015-07-21 15:02
In theory there is not really any down time as the server switch will 
happen quickly. I did'nt realise how long the database upload takes. If 
we don't take the Moodleoff-line, learners may potentially access a 
course, score on an assessment and that would then not be recorded as it 
will be on the "old" database.

My guess is everything will be up and running fairly quickly, but I've 
just given a longer window should there be any issues. We've started it 
as late in the afternoon as we can assuming that there will be fewer 
users accessing content now as there may have been earlier in the day.

**Comment by nick69g** [comment] 2015-07-21 15:08
Checking the logs... only three unique users have logged in today, so I 
do not think this will effect anyone this late in the day...

**Comment by AnnaHavard** [comment] 2015-07-21 15:32
It would be interesting to know how many people actually access their eLearning overnight, I know that some of the Sodexo users for example have used the systems in the late afternoon/early evening.

As I think we talked about in the meeting last week it would have been useful for us to have known that learners would not have access for a certain amount of time and also to have added a note to the hub to say the system wouldn’t be available so people could have either decided to work on it yesterday or tomorrow. I appreciate we don’t have a large number of users but I still don’t want them to complain.

I guess we’ll have to just hope that no-one tries to access it whilst it’s unavailable.





        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image1f731e.JPG@38c45fbb.46ab851c]<http://>

[cid:image3bde91.PNG@4e7499a1.4f989f01]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment] 2015-07-21 15:44
It's a bit frustrating I know.

Ideally we would have had the database downloaded from Vivid and 
immediately uploaded onto the new server which would have taken not too 
long at all and the down time would have been minimal and hardly 
noticed. Vivid should ahve done this work yesterday evening but delayed 
doing it until an hur orso ago, so we had no choice but to put the 
Moodle into maintenance mode to prevent any activity being logged which 
would now not transfer to the new server.

I'd already checked lerner access and last night only one person went in 
after office hours and only 2-3 lerners have been in today.

The databases get uploaded at 5pm, so chances are we will have 
everything up and running in the enxt hour or so.

**Comment by nick69g** [comment] 2015-07-22 08:38
The Hub was put back into live mode yesterday evening as Vivid have delayed uploading the databases.

**Comment by DanielHowells** [comment] 2015-07-22 08:43
Hi Nick, thanks for the update. 

Can you confirm why they delayed the database upload and when the server changeover will take place.

Thanks
Dan

**Comment by nick69g** [comment] 2015-07-22 08:49
Errmmmm.... because they are useless!
Trying to get them "into gear" now. With update when I know.

**Comment by nick69g** [comment] 2015-08-10 13:00
This was not a bug, but how a sub domain behaves.
www.ciwm.co.uk is the mian domain name. clienthub.ciwm.co.uk is a subdomain and as such should not include www. It shouldalways be accessed by typing http://clienthub.ciwm.co.uk
